debate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('extemp.urls')),
]

extemp/urls.py
from django.conf.urls.static import static
from django.urls import path

from .views import *


app_name = 'extemp'
urlpatterns = [
    path('tournament/create/', TournamentCreate.as_view(), name='tournament_create'),
    # path('tournament/<int:pk>/roundgroups/', manage_roundgroups, name='manage_roundgroups'),
    path('tournament/<int:pk>/clock/', TournamentClock.as_view(), name='tournament_clock'),
    path('tournament/<int:pk>/details/', set_tournament_details, name='set_tournament_details'),
    path('tournament/<int:pk>/open/', open_current_rounds, name='open_current_rounds'),
    path('tournament/<int:pk>/close/', close_current_rounds, name='close_current_rounds'),
    path('tournament/<int:pk>/urls/', get_current_urls, name='get_current_urls'),
    path('tournament/<int:pk>/', TournamentDetail.as_view(), name='tournament_detail'),
    path('round/<int:pk>/sections/', manage_sections, name='manage_sections'),
    path('round/<int:pk>/current/', set_current_round, name='set_current_round'),
    path('round/<int:pk>/remove/', remove_current_round, name='remove_current_round'),
    path('round/<int:pk>/open/', open_round, name='open_round'),
    path('round/<int:pk>/close/', close_round, name='close_round'),
    path('round/<int:pk>/admin/manual/', manage_topics, name='manage_topics'),
    path('round/<int:pk>/admin/', bulk_add_topics, name='bulk_add_topics'),
    path('topic/<int:pk>/', TopicDetail.as_view(), name='topic_detail'),
    path('section/<int:pk>/draw/select/', select_topic, name='select_topic'),
    path('section/<int:pk>/draw/', draw_topics, name='draw_topics'),
    path('section/<int:pk>/open/', open_section, name='open_section'),
    path('section/<int:pk>/close/', close_section, name='close_section'),
    path('section/<int:pk>/secret/', SectionDetail.as_view(), name='section_detail_secret'),
    path('section/<int:pk>/', SectionDetailProduction.as_view(), name='section_detail'),
    # path('roundgroup/<int:pk>/open/', open_roundgroup, name='open_roundgroup'),
    # path('roundgroup/<int:pk>/close/', close_roundgroup, name='close_roundgroup'),
    path('', TournamentList.as_view(), name='tournament_list'),
]

extemp/models.py
from datetime import timedelta

from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone

# Create your models here.

class Tournament(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    def get_absolute_url(self):
        return reverse('extemp:tournament_detail', kwargs={'pk': self.pk})

    def get_set_tournament_details_url(self):
        return reverse('extemp:set_tournament_details', kwargs={'pk': self.pk})

    def get_current_rounds(self):
        return Round.objects.filter(event__tournament=self.pk, current=True).order_by('event_id')

    def get_current_topicinstances(self):
        time_threshold = timezone.now() - timedelta(minutes=33)
        return TopicInstance.objects.filter(modified__gt=time_threshold, section__round__current=True, available=False).order_by('modified')

    def __str__(self):
        return f'Tournament: {self.name}'

class Event(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=10)

    def __str__(self):
        return f'{self.name} ({self.code}), {self.tournament}'


class Round(models.Model):
    ROUND_NAMES = (
        ("1", "Round 1",),
        ("2", "Round 2",),
        ("3", "Round 3",),
        ("4", "Round 4",),
        ("5", "Round 5",),
        ("6", "Round 6",),
        ("7", "Round 7",),
        ("8", "Round 8",),
        ("9", "Round 9",),
        ("d", "Doubles",),
        ("o", "Octas",),
        ("q", "Quarters",),
        ("s", "Semis",),
        ("f", "Finals",),
    )
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    name = models.CharField(max_length=1, choices=ROUND_NAMES)
    current = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.event.name}, {self.get_name_display()}'


"""
class RoundGroup(models.Model):
    name = models.CharField(max_length=50)
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    rounds = models.ManyToManyField(Round, blank=True)

    def __str__(self):
        return f'{self.name}'
"""

class Section(models.Model):
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    running_index = models.IntegerField(default=1)
    drawn_topics = models.ManyToManyField('TopicInstance', blank=True, related_name='sections_drawn')
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='sections_in')
    open = models.BooleanField(default=False)

    def claimed_topics(self):
        return self.topicinstance_set.filter(available=False).order_by('index')

    def unclaimed_topics(self):
        return self.topicinstance_set.filter(available=True).order_by('topic__code')

    def __str__(self):
        return f'{self.round} Section {self.name}'

    def get_absolute_url(self):
        return reverse('extemp:section_detail', kwargs={'pk': self.pk})

    def draw_url(self):
        return reverse('extemp:draw_topics', kwargs={'pk': self.pk})


class Topic(models.Model):
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    code = models.IntegerField()
    question = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.round}-{self.code} - {self.question}'

class TopicInstance(models.Model):
    section = models.ForeignKey(Section, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)
    index = models.IntegerField(null=True, blank=True)
    modified = models.DateTimeField(null=True, blank=True)
    name = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return f'Section {self.section.name}, {self.topic}'

    def get_absolute_url(self):
        return reverse('extemp:topic_detail', kwargs={'pk': self.pk})

extemp/forms.py
from django.forms import ModelForm
from .models import *
"""
class RoundGroupForm(ModelForm):
    class Meta:
        model = RoundGroup
        fields = ['name', 'rounds']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if (instance:=kwargs.get('instance')):
            rounds = Round.objects.filter(event__tournament=instance.tournament).order_by('name')
        else:
            rounds = []
        w = self.fields['rounds'].widget
        choices = []
        for round in rounds:
            choices.append((round.id, f'{round.event.code} {round.get_name_display()}'))
        w.choices = choices
        w.attrs['style'] = 'width: 200px;'
        if choices:
            w.attrs['size'] = min(10, len(choices))
"""

extemp/views.py
from datetime import datetime
from random import sample

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin as LRM, UserPassesTestMixin as UPTM
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.forms import modelformset_factory, inlineformset_factory, ModelForm
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.utils import timezone
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from .models import *
from .forms import *


class LoginRequiredMixin(LRM):
    raise_exception = True


class AdminRequiredMixin(UPTM):
    raise_exception = True
    def test_func(self):
        return self.request.user.is_authenticated and self.request.user.is_superuser


def admin_test(user):
    if user.is_anonymous or not user.is_superuser:
        raise PermissionDenied


def open_test(user, section):
    if not(user.is_authenticated and user.is_superuser) and not section.open:
        raise PermissionDenied


def current_test(user, section):
    if not(user.is_authenticated and user.is_superuser) and not section.round.current:
        raise PermissionDenied


def open_current_rounds(request, pk):
    admin_test(request.user)
    tournament = get_object_or_404(Tournament, pk=pk)
    for round in tournament.get_current_rounds():
        for section in round.section_set.all():
            section.open = True
            section.save()
    return redirect(tournament)


def close_current_rounds(request, pk):
    admin_test(request.user)
    tournament = get_object_or_404(Tournament, pk=pk)
    for round in tournament.get_current_rounds():
        for section in round.section_set.all():
            section.open = False
            section.save()
    return redirect(tournament)


def get_current_urls(request, pk):
    admin_test(request.user)
    tournament = get_object_or_404(Tournament, pk=pk)
    return render(request, 'extemp/get_current_urls.html', context={'tournament': tournament})


"""
def open_roundgroup(request, pk):
    admin_test(request.user)
    roundgroup = get_object_or_404(RoundGroup, pk=pk)
    for round in roundgroup.rounds.all():
        for section in round.section_set.all():
            section.open = True
            section.save()
    return redirect('extemp:manage_roundgroups', pk=roundgroup.tournament.pk)


def close_roundgroup(request, pk):
    admin_test(request.user)
    roundgroup = get_object_or_404(RoundGroup, pk=pk)
    for round in roundgroup.rounds.all():
        for section in round.section_set.all():
            section.open = False
            section.save()
    return redirect('extemp:manage_roundgroups', pk=roundgroup.tournament.pk)
"""


def set_current_round(request, pk):
    admin_test(request.user)
    round = get_object_or_404(Round, pk=pk)
    round.event.round_set.update(current=False)
    round.current = True
    round.save()
    return redirect(round.event.tournament)


def remove_current_round(request, pk):
    admin_test(request.user)
    round = get_object_or_404(Round, pk=pk)
    round.current = False
    round.save()
    return redirect(round.event.tournament)


def open_round(request, pk):
    admin_test(request.user)
    round = get_object_or_404(Round, pk=pk)
    for section in round.section_set.all():
        section.open = True
        section.save()
    return redirect(round.event.tournament)


def close_round(request, pk):
    admin_test(request.user)
    round = get_object_or_404(Round, pk=pk)
    for section in round.section_set.all():
        section.open = False
        section.save()
    return redirect(round.event.tournament)


def open_section(request, pk):
    admin_test(request.user)
    section = get_object_or_404(Section, pk=pk)
    section.open = True
    section.save()
    return redirect(section)


def close_section(request, pk):
    admin_test(request.user)
    section = get_object_or_404(Section, pk=pk)
    section.open = False
    section.save()
    return redirect(section)


def manage_sections(request, pk):
    admin_test(request.user)
    round = get_object_or_404(Round, pk=pk)
    SectionFormSet = inlineformset_factory(Round, Section, fields=['name'], extra=3, can_delete=True)
    if request.method == "POST":
        sectionformset = SectionFormSet(request.POST, instance=round)
        if sectionformset.is_valid():
            sections = sectionformset.save()
            for section in sections:
                for topic in round.topic_set.all():
                    section.topicinstance_set.create(topic=topic)
            return redirect('extemp:tournament_detail', pk=round.event.tournament.pk)
    else:
        sectionformset = SectionFormSet(instance=round)
    return render(request, 'extemp/manage_sections.html', context={'sectionformset': sectionformset, 'round': round})


"""
def manage_roundgroups(request, pk):
    admin_test(request.user)
    tournament = get_object_or_404(Tournament, pk=pk)
    RoundGroupFormSet = inlineformset_factory(Tournament, RoundGroup, form=RoundGroupForm, extra=3, can_delete=True)
    if request.method == "POST":
        roundgroupformset = RoundGroupFormSet(request.POST, instance=tournament)
        if roundgroupformset.is_valid():
            roundgroupformset.save()
            return redirect(tournament)
    else:
        roundgroupformset = RoundGroupFormSet(instance=tournament)
    return render(request, 'extemp/manage_roundgroups.html', context={'roundgroupformset': roundgroupformset, 'tournament': tournament})
"""

def manage_topics(request, pk):
    admin_test(request.user)
    round = get_object_or_404(Round, pk=pk)
    if request.method == 'POST':
        for x in range(1, 31):
            p = request.POST.get(f'pk-{x}')
            c = request.POST.get(f'code-{x}')
            q = request.POST.get(f'question-{x}')
            if not p:
                if c and q:
                    round.topic_set.create(code=c, question=q)
                    for section in round.section_set.all():
                        section.topicinstance_set.create(topic=t)
            elif not c and not q:
                Topic.objects.filter(pk=p).delete()
            elif c and q:
                Topic.objects.filter(pk=p).update(code=c, question=q)
        return redirect(round.event.tournament)
    topics = (*round.topic_set.order_by('code'), *([] for x in range(30-round.topic_set.count())))
    return render(request, 'extemp/manage_topics.html', context={'round': round, 'topics': topics})


def bulk_add_topics(request, pk):
    admin_test(request.user)
    round = get_object_or_404(Round, pk=pk)
    if request.method == 'POST' and (c:=request.POST.get('topics')):
        round.topic_set.all().delete()
        lines = c.splitlines()
        for i, line in enumerate(lines):
            if line:
                t = round.topic_set.create(code=i+1, question=line)
                for section in round.section_set.all():
                    section.topicinstance_set.create(topic=t)
        return redirect(round.event.tournament)
    topics = round.topic_set.order_by('code')
    return render(request, 'extemp/bulk_add_topics.html', context={'round': round, 'topics': topics})


def draw_topics(request, pk):
    section = get_object_or_404(Section, pk=pk)
    current_test(request.user, section)
    if section.drawn_topics.exists():
        return redirect('extemp:select_topic', pk=pk)
    if request.method == 'POST' and (y:=request.POST.get('yes')) and (name:=request.POST.get('name')) and section.open:
        topics = sample(list(section.unclaimed_topics()), 3)
        for topic in topics:
            topic.modified = datetime.now(tz=timezone.utc)
            topic.name = name
            topic.save()
        section.drawn_topics.add(*topics)
        return redirect('extemp:select_topic', pk=pk)
    return render(request, 'extemp/draw_topics.html', context={'section': section})


def select_topic(request, pk):
    section = get_object_or_404(Section, pk=pk)
    open_test(request.user, section)
    if not section.drawn_topics.exists():
        return redirect('extemp:draw_topics', pk=pk)
    topics = section.drawn_topics.all()
    if request.method == 'POST' and (t:=request.POST.get('topic')):
        topic_list = topics.filter(pk=t)
        if topic_list.exists():
            topic = topic_list.get()
            topic.index = section.running_index
            topic.available = False
            topic.save()
            section.running_index += 1
            section.open = False
            section.save()
            section.drawn_topics.clear()
            # return redirect(topic)
            return render(request, 'extemp/topicinstance_detail.html', context={'topicinstance': topic})
    return render(request, 'extemp/select_topic.html', context={'topics': topics, 'section': section})


class ActivationRequiredMixin:
    pass


class TournamentCreate(AdminRequiredMixin, CreateView):
    model = Tournament
    fields = ["name"]

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.save()
        return redirect(form.instance.get_set_tournament_details_url())


def set_tournament_details(request, pk):
    admin_test(request.user)
    tournament = get_object_or_404(Tournament, pk=pk)
    choices = Round.ROUND_NAMES
    if request.method == "POST":
        keys = {x:{} for x in range(6)}
        for key in request.POST.keys():
            val = request.POST.get(key)
            if val is None or key == "csrfmiddlewaretoken":
                continue
            a, b = key.split("-")
            keys[int(a)][b] = val
        for row in keys.keys():
            name = keys[row]["name"]
            code = keys[row]["code"]

extemp/templates/extemp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Extemp Draw</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="container pt-5 pb-5">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'extemp:tournament_list' %}">
                <img src="/favicon.ico" width="30" height="30" class="d-inline-block align-top" alt="">
                Extemp Draw
            </a>
          
            {% if user.is_authenticated and user.is_superuser %}
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <a class="btn btn-outline-primary" role="button" href="{% url 'extemp:tournament_create' %}">Create</a>
            </div>
            {% endif %}
          </nav>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>
    

extemp/templates/extemp/base_competitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Extemp Draw</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="container pt-5 pb-5">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">
                <img src="/favicon.ico" width="30" height="30" class="d-inline-block align-top" alt="">
                Extemp Draw
            </a>
          </nav>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>
    

extemp/templates/extemp/base_public.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Extemp Draw</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
</head>
<body>
    <div class="container pt-5 pb-5">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">
                <img src="/favicon.ico" width="30" height="30" class="d-inline-block align-top" alt="">
                Extemp Draw
            </a>
          </nav>
          <div class="container">
              {% block content %}
              {% endblock %}
          </div>
    </div>
</body>
</html>
    

extemp/templates/extemp/bulk_add_topics.html
{% extends 'extemp/base.html' %}
{% block head %}
{% endblock %}
{% block content %}
<h1><a href="{% url 'extemp:tournament_detail' round.event.tournament.pk %}">{{ round.event.tournament.name }} - Extemp Dashboard</a></h1>
<h1>{{round}}</h1>
<h2>Bulk Add Topics <a href="{% url 'extemp:manage_topics' round.pk %}">Manually Manage Topics</a></h2>
<p>Paste topics here (one per line, just the question)</p>
<form action="{% url 'extemp:bulk_add_topics' round.pk %}" method="post">
{% csrf_token %}
<textarea name="topics" rows="20" cols="100" required>{% for topic in topics %}
{{ topic.question }}{% empty %}{% endfor %}</textarea>
<br>
<input type="checkbox" required id="yes" /><label for="yes">I acknowledge that all current topics will be deleted and replaced with the new topics entered above.</label>
<br>
<br>
<input type="submit" class="btn btn-primary" value="Submit" />
</form>
{% endblock %}

extemp/templates/extemp/draw_topics.html
{% extends 'extemp/base_public.html' %}
{% block content %}
<h1>{{ section.round.event.tournament.name }} Extemp Draw</h1>
<h1>{{ section.round.event.name }} {{ section.round.get_name_display }}</h1>
<form action="{% url 'extemp:draw_topics' section.pk %}" method="post">
{% csrf_token %}
<input name="yes" type="hidden" value="yes" />
<div class="form-group">
    <label for="name" class="form-label">Name</label>
    <input type="text" class="form-control" id="name" name="name" required />
</div>
<div class="row">
    <div class="col-sm-11">Please only click this button if you are ready to draw for {{section.round}} Section {{section.name}}, Speaker {{section.running_index}}</div>
    <div class="col-sm-1">
        <input class="btn btn-primary float-sm-right" type="submit" value="Draw">
    </div>
</div>
</form>
{% endblock %}

extemp/templates/extemp/manage_sections.html
{% extends 'extemp/base.html' %}
{% block head %}
<style>
div.form-group input[type=text] {
    width: 100%;
}
</style>
{% endblock %}
{% block content %}
<h1><a href="{% url 'extemp:tournament_detail' round.event.tournament.pk %}">{{ round.event.tournament.name }} - Extemp Dashboard</a></h1>
<h1>{{round}}</h1>
<h2>Manage Sections</h2>
<form method="post" action="{% url 'extemp:manage_sections' round.pk %}">
{% csrf_token %}
{{ sectionformset.management_form }}
<div class="row">
    <div class="col-sm-11">
        Name
    </div>
    <div class="col-sm-1">
        Delete
    </div>
</div>
{% for form in sectionformset %}
{% for hidden in form.hidden_fields %}
    {{ hidden }}
{% endfor %}
<div class="row">
    <div class="col-sm-11">
        <div class="form-group">
            {{form.name}}
        </div>
    </div>
    <div class="col-sm-1">
        <div class="form-group">
            {{form.DELETE}}
        </div>
    </div>
</div>
{% endfor %}
<input type="submit" value="Save" />
</form>

{% endblock %}

extemp/templates/extemp/round_update.html
{% extends 'extemp/base.html' %}
{% block content %}
<h1><a href="{% url 'extemp:tournament_detail' round.event.tournament.pk %}">{{ round.event.tournament.name }} - Extemp Dashboard</a></h1>
<h1>Round: {{ round.event.name}} {{round.code}}</h1>
<h2>Manage Sections</h2>
<form method="post" action="{% url 'extemp:round_update' round.pk %}">
{% csrf_token %}
{{ sectionformset.management_form }}
<table>
{% for form in sectionformset %}
<tr><td>{{form.as_p}}</td></tr>
{% endfor %}
</table>
<input type="submit" value="Save" />
</form>

{% endblock %}

extemp/templates/extemp/section_detail.html
{% extends 'extemp/base.html' %}
{% block content %}
<h1><a href="{% url 'extemp:tournament_detail' section.round.event.tournament.pk %}">{{ section.round.event.tournament.name }} - Extemp Dashboard</a></h1>
<h1>{{section.round}}, Section: {{ section.name }}</h1>
<h2>Claimed Topics <a href="{% url 'extemp:section_detail' section.pk %}">Production</a></h2>
{% for instance in section.claimed_topics %}
<p>Speaker {{ instance.index }} ({{ instance.name }})'s Topic: {{ instance.topic }} - was drawn {{ instance.modified | timesince }} ago</p>
{% endfor %}
<h2>Unclaimed Topics <a href="{% url 'extemp:draw_topics' section.pk %}">Draw Topics</a> {% if section.open %}<a href="{% url 'extemp:close_section' section.pk %}">Close Envelopes</a>{% else %}<a href="{% url 'extemp:open_section' section.pk %}">Open Envelopes</a>{% endif %}</h2>
<ul>
{% for instance in section.unclaimed_topics %}
<li>{{ instance }}</li>
{% endfor %}
</ul>



{% endblock %}

extemp/templates/extemp/section_detail_production.html
{% extends 'extemp/base.html' %}
{% block content %}
<h1><a href="{% url 'extemp:tournament_detail' section.round.event.tournament.pk %}">{{ section.round.event.tournament.name }} - Extemp Dashboard</a></h1>
<h1>{{section.round}}, Section: {{ section.name }}</h1>
<h2>Claimed Topics {% if user.is_superuser %}<a href="{% url 'extemp:section_detail_secret' section.pk %}">Secret</a>{% endif %}</h2>
<p>Empty for security</p>
<h2>Unclaimed Topics{% if section.open %} <a href="{% url 'extemp:draw_topics' section.pk %}">Draw Topics</a>{% endif %}</h2>
<p>Currently awaiting speaker #{{ section.running_index }}.</p>



{% endblock %}

extemp/templates/extemp/select_topic.html
{% extends 'extemp/base_public.html' %}
{% block content %}
<form action="{% url 'extemp:select_topic' section.pk %}" method="post">
{% csrf_token %}
{% for topic in topics %}
<hr>
<div class="row">
    <div class="col-sm-12">
        <div class="form-check">
            <input class="form-check-input" type="radio" name="topic" value="{{topic.pk}}" id="{{topic.pk}}" /><label for="{{topic.pk}}">
            <label class="form-check-label" for="{{topic.pk}}">{{ topic.topic.round }}-{{ topic.topic.code }} - {{ topic.topic.question }}</label>
        </div>
    </div>
</div>
{% endfor %}
<div class="row">
    <div class="col-sm-12">
        <input class="btn btn-primary float-sm-right" type="submit" value="Submit">
    </div>
</div>
<hr>
</form>

<h1>DO NOT TAKE A PICTURE OF THIS PAGE.  DO NOT TAKE A PICTURE OF THIS PAGE.</h1>
<h1>HIT SUBMIT FIRST, THEN YOU CAN TAKE A PICTURE OF YOUR TOPIC ON THE NEXT PAGE</h1>
{% endblock %}

extemp/templates/extemp/topicinstance_detail.html
{% extends 'extemp/base_public.html' %}
{% block content %}
<h1>You are speaker {{ topicinstance.index }} in section {{ topicinstance.section.name }}.</h1>
<h1>You selected topic {{ topicinstance.topic }}</h1>
<h1>Please take a screenshot of this page or copy the question.</h1>
{% endblock %}

extemp/templates/extemp/tournament_form.html
{% extends 'extemp/base.html' %}
{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock %}

extemp/templates/extemp/tournament_list.html
{% extends 'extemp/base.html' %}
{% block content %}
<div class="row d-flex">
    <div class="col-sm">
        <h1>Tournaments</h1>
    </div>
</div>

{% for tournament in tournament_list %}
<h2><a href="{% url 'extemp:tournament_detail' tournament.pk %}">{{ tournament.name }}</a></h2>
{% empty %}
<p>empty</p>
{% endfor %}
{% endblock %}